spring:
    datasource: 
        url: jdbc:mysql://localhost:3306/dbprojet?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username : root
        password :
        
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8083

